name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: sudo
      run: sudo chown -R ubuntu:ubuntu ubuntu
    - name: make
      run: make
    - name: make iso
      run: ./createimage.sh
