name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: iso
      run: ./createimage.sh 
    - name: Upload a Build Artifact(myos.elf)
      uses: actions/upload-artifact@v2.1.4
      with:
          name: myos.elf
          path: myos.elf
